apiVersion: v1
kind: ConfigMap
metadata:
  name: olivetin-config
data:
  config.yaml: |
    actions:
      - title: "Hello world!"
        shell: echo 'Hello World!'
      
      - title: ping google.com
        shell: ping 8.8.8.8 -c 10
        icon: ping
        timeout: 3
      
      - title: Ping host
        shell: ping {{ host }} -c {{ count }}
        icon: ping
        arguments:
        - name: host
          title: host
          type: ascii_identifier
          default: google.com
      
