# This creates the K8s Service
apiVersion: v1
kind: Service
metadata:
  name: netdemo-service
  labels:
    app: netdemo
spec:
  ports:
    # the port that this service should serve on
    - port: 1337
  selector:
    app: netdemo
  type: LoadBalancer