apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netdemo
  template:
    metadata:
      labels:
        app: netdemo
    spec:
      containers:
      - name: net-demo
        image: wbitt/network-multitool
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: net-demo-svc
  labels:
    app: netdemo
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    app: netdemo
  type: LoadBalancer
